language: python
python:
  - "2.7.8"
services:
  - docker
before_install:
  - docker build -t ubuntu-python .
script:
  - docker run --rm ubuntu-python zip
  - docker run --rm ubuntu-python aws --version
